//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiparisApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARI
    {
        public int ID { get; set; }
        public string CARI_ADI { get; set; }
        public string ULKE { get; set; }
        public Nullable<int> EKLEYEN_ID { get; set; }
        public Nullable<System.DateTime> EKLENME_TARIHI { get; set; }
        public Nullable<int> GUNCELLEYEN_ID { get; set; }
        public Nullable<System.DateTime> GUNCELLENME_TARIHI { get; set; }
        public Nullable<int> AKTIF { get; set; }
    }
}
