//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiparisApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KULLANICI
    {
        public int ID { get; set; }
        public string KULLANICI_ADI { get; set; }
        public string SIFRE { get; set; }
        public string AD { get; set; }
        public string SOYAD { get; set; }
        public string BIRIM { get; set; }
        public string SEVIYE { get; set; }
        public Nullable<int> AKTIF { get; set; }
    }
}
