//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiparisApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPARIS
    {
        public int ID { get; set; }
        public string PROJE_NO { get; set; }
        public Nullable<int> SERI_NO { get; set; }
        public Nullable<int> GUC { get; set; }
        public Nullable<int> CARI_ID { get; set; }
        public Nullable<int> SIPARIS_ADETI { get; set; }
        public Nullable<System.DateTime> SIPARIS_TARIHI { get; set; }
        public Nullable<int> KULLANICI_ID { get; set; }
        public Nullable<int> AKTIF { get; set; }
    }
}
